# Generated by Django 5.2.7 on 2025-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group', 'Group Chat'), ('personal', 'Personal Chat')], default='group', max_length=20),
        ),
    ]
