# Generated by Django 5.2.7 on 2025-11-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café'), ('lounge', 'Lounge'), ('charging_station', 'Charging Station'), ('shop', 'Shop'), ('restroom', 'Restroom'), ('gate', 'Gate'), ('information', 'Information Desk')], max_length=30)),
                ('terminal', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('price_range', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('is_24_hours', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['airport_code', 'place_type'], name='recommendat_airport_1303ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.airportplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['distance_meters', '-place__rating'],
            },
        ),
    ]
