# Generated by Django 5.2.7 on 2025-11-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('prefer_first_time_travelers', models.BooleanField(default=False)),
                ('prefer_experienced_travelers', models.BooleanField(default=False)),
                ('require_common_interests', models.BooleanField(default=False)),
                ('min_common_interests', models.IntegerField(default=1)),
                ('prefer_business_travelers', models.BooleanField(default=False)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_filter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('same_departure', 'Same Departure'), ('same_layover', 'Same Layover'), ('same_destination', 'Same Destination'), ('departure_layover', 'Departure is Layover'), ('layover_departure', 'Layover is Departure'), ('same_route', 'Same Route')], max_length=30)),
                ('matching_airport', models.CharField(max_length=10)),
                ('matching_city', models.CharField(max_length=100)),
                ('overlap_start', models.DateTimeField()),
                ('overlap_end', models.DateTimeField()),
                ('overlap_duration_hours', models.FloatField()),
                ('match_score', models.FloatField(default=0.0)),
                ('common_interests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('liked', 'Liked'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('user1_liked', models.BooleanField(default=False)),
                ('user2_liked', models.BooleanField(default=False)),
                ('user1_viewed', models.BooleanField(default=False)),
                ('user2_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('flight1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_flight1', to='flights.flight')),
                ('flight2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_flight2', to='flights.flight')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user1', 'status'], name='matching_ma_user1_i_58bf32_idx'), models.Index(fields=['user2', 'status'], name='matching_ma_user2_i_516af4_idx'), models.Index(fields=['match_type', 'matching_airport'], name='matching_ma_match_t_7333e5_idx')],
                'unique_together': {('user1', 'user2', 'flight1', 'flight2')},
            },
        ),
    ]
