# Generated by Django 5.2.7 on 2025-11-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_experience', models.CharField(blank=True, choices=[('first_time', 'First Time Traveler'), ('occasional', 'Occasional Traveler'), ('frequent', 'Frequent Traveler'), ('business', 'Business Traveler')], max_length=20)),
                ('is_first_international', models.BooleanField(default=False)),
                ('looking_for_guide', models.BooleanField(default=False)),
                ('offering_guidance', models.BooleanField(default=False)),
                ('preferred_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('open_to_business', models.BooleanField(default=False)),
                ('business_interests', models.TextField(blank=True)),
                ('open_to_socializing', models.BooleanField(default=True)),
                ('preferred_activities', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('aircraft', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_airport', models.CharField(max_length=10)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_country', models.CharField(blank=True, max_length=100)),
                ('departure_terminal', models.CharField(blank=True, max_length=20)),
                ('departure_gate', models.CharField(blank=True, max_length=20)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=10)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_country', models.CharField(blank=True, max_length=100)),
                ('arrival_terminal', models.CharField(blank=True, max_length=20)),
                ('arrival_gate', models.CharField(blank=True, max_length=20)),
                ('arrival_datetime', models.DateTimeField()),
                ('has_layover', models.BooleanField(default=False)),
                ('layover_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('layover_city', models.CharField(blank=True, max_length=100, null=True)),
                ('layover_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('layover_start', models.DateTimeField(blank=True, null=True)),
                ('layover_end', models.DateTimeField(blank=True, null=True)),
                ('layover_duration_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('delayed', 'Delayed'), ('in_flight', 'In Flight'), ('landed', 'Landed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('seat', models.CharField(blank=True, max_length=10)),
                ('booking_reference', models.CharField(blank=True, max_length=50)),
                ('travel_class', models.CharField(default='economy', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('looking_for_company', models.BooleanField(default=False)),
                ('open_to_meeting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['departure_airport', 'departure_datetime'], name='flights_fli_departu_ca083a_idx'), models.Index(fields=['arrival_airport', 'arrival_datetime'], name='flights_fli_arrival_274499_idx'), models.Index(fields=['layover_airport', 'layover_start', 'layover_end'], name='flights_fli_layover_448702_idx'), models.Index(fields=['user', 'is_visible'], name='flights_fli_user_id_f29ef1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
